#!/bin/bash
count () {
  local dir="$1"
  local count=0
  for file in "$dir"/* "$dir"/.[!.]*; do
    if [[ -d "$file" ]]; then
      if [[ "$file" != "$dir/." && "$file" != "$dir/.." ]]; then
        count=$((count+1))
        count=$((count+$(count "$file")))
      fi
    fi
  done
  echo $count
}
